name: example
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  italia_ui_kit:
    path: ../
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: TitilliumWeb
      fonts:
        - asset: fonts/TitilliumWeb/ExtraLight.ttf
          weight: 200
        - asset: fonts/TitilliumWeb/ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/TitilliumWeb/Light.ttf
          weight: 300
        - asset: fonts/TitilliumWeb/LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/TitilliumWeb/Regular.ttf
          weight: 400
        - asset: fonts/TitilliumWeb/Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/TitilliumWeb/SemiBold.ttf
          weight: 600
        - asset: fonts/TitilliumWeb/SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/TitilliumWeb/Bold.ttf
          weight: 700
        - asset: fonts/TitilliumWeb/BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/TitilliumWeb/Black.ttf
          weight: 900